name: NASA Project CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa

    strategy:
      matrix: 
        node_version: [14.x, 16.x, 18.x]
        mongodb-version: ['4.4', '5.0', '6.0']
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Use MongoDB from GitHub Actions
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 42069

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build --prefix client

      - name: Run tests
        run: npm test

  deploy:
    needs: build
